name: Build App Image

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
